name: "Build Dev"
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
jobs:
  build:
    name: Build Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --flavor dev -t lib/main_dev.dart --split-per-abi
      - name: push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}